<?php 
/*
Plugin Name: WebePartners
Plugin URI: https://www.worzala.pl/webepartners
Description: 
Version: 0.0.1
Author: PawelWorzala
Author URI: https://www.worzala.pl
Text Domain: w
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}








add_action('admin_menu', 'test_plugin_setup_menu');
 
function test_plugin_setup_menu(){
    add_menu_page( 'Test Plugin Page', 'Test Plugin', 'manage_options', 'test-plugin', 'test_init' );
}
 
function test_init(){
    echo "<h1>Hello World!</h1>";
}

//https://service.weben1.com/xml/a1b89ba2-c4b8-4516-a10c-70cd5c0e4148.xml